-- MUTATING — not run in this repo. Run as the dedicated RAGAPP user only.
-- Every block is delimited by a slash for setup.py/SQLcl.
-- Rollback: drop REFS_HYBRID_IDX, DOC_CHUNKS_HNSW, DOC_CHUNKS, DOC_TAB,
-- and DBMS_VECTOR.DROP_ONNX_MODEL('ALL_MINILM_L12_V2', true).
-- https://docs.oracle.com/en/database/oracle/oracle-database/26/vecse/load_onnx_model_cloud.html
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_mining_models WHERE model_name='ALL_MINILM_L12_V2';
  IF n=0 THEN
    DBMS_VECTOR.LOAD_ONNX_MODEL_CLOUD(model_name=>'ALL_MINILM_L12_V2', credential=>NULL, uri=>:model_uri);
  END IF;
END;
/
-- https://docs.oracle.com/en/database/oracle/oracle-database/26/vecse/create-tables-using-vector-data-type.html
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE doc_tab (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, doc_name VARCHAR2(200) UNIQUE, text CLOB)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
-- https://docs.oracle.com/en/database/oracle/oracle-database/26/vecse/create-tables-using-vector-data-type.html
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE doc_chunks (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, doc_id NUMBER REFERENCES doc_tab(id), chunk_offset NUMBER, chunk_text CLOB, embedding VECTOR(384,FLOAT32))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
